default:
  image: alpine:latest
stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN in workspace dir $CI_PROJECT_DIR"

test-job1: 
  stage: test
  services:
    - name: mysql:latest
      alias: mysql
      variables:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
  image: python:3.9.12-slim
  script:
    - echo "This job tests"
    - sleep 10

deploy-prod:
  stage: deploy
  script:
    - echo "This job delployed $CI_COMMIT_REF_NAME from $CI_COMMIT_BRANCH branch, due to $CI_PIPELINE_SOURCE. REF_SLUG is $CI_COMMIT_REF_SLUG"
    - printenv
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual

.docker-build:
  stage: build
  script:
    - docker build -t my-image:$CI_COMMENT_REF_SLUG
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    changes:
      - Dockerfile
    when: manual
    allow_failure: true
